// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: server_communication.proto
// Protobuf C++ Version: 5.29.3

#include "server_communication.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace leaftest {

inline constexpr TimeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : server_time_ms_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TimeResponse::TimeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TimeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimeResponseDefaultTypeInternal() {}
  union {
    TimeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimeResponseDefaultTypeInternal _TimeResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR TimeRequest::TimeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TimeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimeRequestDefaultTypeInternal() {}
  union {
    TimeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimeRequestDefaultTypeInternal _TimeRequest_default_instance_;
}  // namespace leaftest
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_5fcommunication_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_5fcommunication_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_5fcommunication_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::leaftest::TimeRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::leaftest::TimeResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::leaftest::TimeResponse, _impl_.server_time_ms_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::leaftest::TimeRequest)},
        {8, -1, -1, sizeof(::leaftest::TimeResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::leaftest::_TimeRequest_default_instance_._instance,
    &::leaftest::_TimeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_server_5fcommunication_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032server_communication.proto\022\010leaftest\"\r"
    "\n\013TimeRequest\"&\n\014TimeResponse\022\026\n\016server_"
    "time_ms\030\001 \001(\0032W\n\023ServerCommunication\022@\n\r"
    "GetServerTime\022\025.leaftest.TimeRequest\032\026.l"
    "eaftest.TimeResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_server_5fcommunication_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_server_5fcommunication_2eproto = {
    false,
    false,
    190,
    descriptor_table_protodef_server_5fcommunication_2eproto,
    "server_communication.proto",
    &descriptor_table_server_5fcommunication_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_server_5fcommunication_2eproto::offsets,
    file_level_enum_descriptors_server_5fcommunication_2eproto,
    file_level_service_descriptors_server_5fcommunication_2eproto,
};
namespace leaftest {
// ===================================================================

class TimeRequest::_Internal {
 public:
};

TimeRequest::TimeRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:leaftest.TimeRequest)
}
TimeRequest::TimeRequest(
    ::google::protobuf::Arena* arena,
    const TimeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TimeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:leaftest.TimeRequest)
}

inline void* TimeRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TimeRequest(arena);
}
constexpr auto TimeRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TimeRequest),
                                            alignof(TimeRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TimeRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TimeRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TimeRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<TimeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TimeRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<TimeRequest>(), &TimeRequest::ByteSizeLong,
            &TimeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TimeRequest, _impl_._cached_size_),
        false,
    },
    &TimeRequest::kDescriptorMethods,
    &descriptor_table_server_5fcommunication_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TimeRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> TimeRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::leaftest::TimeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata TimeRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TimeResponse::_Internal {
 public:
};

TimeResponse::TimeResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:leaftest.TimeResponse)
}
TimeResponse::TimeResponse(
    ::google::protobuf::Arena* arena, const TimeResponse& from)
    : TimeResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE TimeResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TimeResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_time_ms_ = {};
}
TimeResponse::~TimeResponse() {
  // @@protoc_insertion_point(destructor:leaftest.TimeResponse)
  SharedDtor(*this);
}
inline void TimeResponse::SharedDtor(MessageLite& self) {
  TimeResponse& this_ = static_cast<TimeResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TimeResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TimeResponse(arena);
}
constexpr auto TimeResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TimeResponse),
                                            alignof(TimeResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TimeResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TimeResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TimeResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TimeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TimeResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TimeResponse>(), &TimeResponse::ByteSizeLong,
            &TimeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TimeResponse, _impl_._cached_size_),
        false,
    },
    &TimeResponse::kDescriptorMethods,
    &descriptor_table_server_5fcommunication_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TimeResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> TimeResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::leaftest::TimeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 server_time_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TimeResponse, _impl_.server_time_ms_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TimeResponse, _impl_.server_time_ms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 server_time_ms = 1;
    {PROTOBUF_FIELD_OFFSET(TimeResponse, _impl_.server_time_ms_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void TimeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:leaftest.TimeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.server_time_ms_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TimeResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TimeResponse& this_ = static_cast<const TimeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TimeResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TimeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:leaftest.TimeResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 server_time_ms = 1;
          if (this_._internal_server_time_ms() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_server_time_ms(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:leaftest.TimeResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TimeResponse::ByteSizeLong(const MessageLite& base) {
          const TimeResponse& this_ = static_cast<const TimeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TimeResponse::ByteSizeLong() const {
          const TimeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:leaftest.TimeResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int64 server_time_ms = 1;
            if (this_._internal_server_time_ms() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_server_time_ms());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TimeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TimeResponse*>(&to_msg);
  auto& from = static_cast<const TimeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:leaftest.TimeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_server_time_ms() != 0) {
    _this->_impl_.server_time_ms_ = from._impl_.server_time_ms_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TimeResponse::CopyFrom(const TimeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:leaftest.TimeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TimeResponse::InternalSwap(TimeResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.server_time_ms_, other->_impl_.server_time_ms_);
}

::google::protobuf::Metadata TimeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace leaftest
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_server_5fcommunication_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
