// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_test.proto

#include "server_test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace leaftest {
PROTOBUF_CONSTEXPR TimeRequest::TimeRequest(
    ::_pbi::ConstantInitialized){}
struct TimeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimeRequestDefaultTypeInternal() {}
  union {
    TimeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimeRequestDefaultTypeInternal _TimeRequest_default_instance_;
PROTOBUF_CONSTEXPR TimeResponse::TimeResponse(
    ::_pbi::ConstantInitialized)
  : server_time_ms_(int64_t{0}){}
struct TimeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimeResponseDefaultTypeInternal() {}
  union {
    TimeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimeResponseDefaultTypeInternal _TimeResponse_default_instance_;
}  // namespace leaftest
static ::_pb::Metadata file_level_metadata_server_5ftest_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_server_5ftest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_server_5ftest_2eproto = nullptr;

const uint32_t TableStruct_server_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leaftest::TimeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leaftest::TimeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::leaftest::TimeResponse, server_time_ms_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::leaftest::TimeRequest)},
  { 6, -1, -1, sizeof(::leaftest::TimeResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::leaftest::_TimeRequest_default_instance_._instance,
  &::leaftest::_TimeResponse_default_instance_._instance,
};

const char descriptor_table_protodef_server_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021server_test.proto\022\010leaftest\"\r\n\013TimeReq"
  "uest\"&\n\014TimeResponse\022\026\n\016server_time_ms\030\001"
  " \001(\0032N\n\nServerTest\022@\n\rGetServerTime\022\025.le"
  "aftest.TimeRequest\032\026.leaftest.TimeRespon"
  "se\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_server_5ftest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_5ftest_2eproto = {
    false, false, 172, descriptor_table_protodef_server_5ftest_2eproto,
    "server_test.proto",
    &descriptor_table_server_5ftest_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_server_5ftest_2eproto::offsets,
    file_level_metadata_server_5ftest_2eproto, file_level_enum_descriptors_server_5ftest_2eproto,
    file_level_service_descriptors_server_5ftest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_5ftest_2eproto_getter() {
  return &descriptor_table_server_5ftest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_server_5ftest_2eproto(&descriptor_table_server_5ftest_2eproto);
namespace leaftest {

// ===================================================================

class TimeRequest::_Internal {
 public:
};

TimeRequest::TimeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:leaftest.TimeRequest)
}
TimeRequest::TimeRequest(const TimeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:leaftest.TimeRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TimeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TimeRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata TimeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5ftest_2eproto_getter, &descriptor_table_server_5ftest_2eproto_once,
      file_level_metadata_server_5ftest_2eproto[0]);
}

// ===================================================================

class TimeResponse::_Internal {
 public:
};

TimeResponse::TimeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:leaftest.TimeResponse)
}
TimeResponse::TimeResponse(const TimeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  server_time_ms_ = from.server_time_ms_;
  // @@protoc_insertion_point(copy_constructor:leaftest.TimeResponse)
}

inline void TimeResponse::SharedCtor() {
server_time_ms_ = int64_t{0};
}

TimeResponse::~TimeResponse() {
  // @@protoc_insertion_point(destructor:leaftest.TimeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TimeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TimeResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TimeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:leaftest.TimeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  server_time_ms_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TimeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 server_time_ms = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          server_time_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TimeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:leaftest.TimeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 server_time_ms = 1;
  if (this->_internal_server_time_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_server_time_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:leaftest.TimeResponse)
  return target;
}

size_t TimeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:leaftest.TimeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 server_time_ms = 1;
  if (this->_internal_server_time_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_server_time_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TimeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TimeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TimeResponse::GetClassData() const { return &_class_data_; }

void TimeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TimeResponse *>(to)->MergeFrom(
      static_cast<const TimeResponse &>(from));
}


void TimeResponse::MergeFrom(const TimeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:leaftest.TimeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_server_time_ms() != 0) {
    _internal_set_server_time_ms(from._internal_server_time_ms());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TimeResponse::CopyFrom(const TimeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:leaftest.TimeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimeResponse::IsInitialized() const {
  return true;
}

void TimeResponse::InternalSwap(TimeResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(server_time_ms_, other->server_time_ms_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TimeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5ftest_2eproto_getter, &descriptor_table_server_5ftest_2eproto_once,
      file_level_metadata_server_5ftest_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace leaftest
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::leaftest::TimeRequest*
Arena::CreateMaybeMessage< ::leaftest::TimeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leaftest::TimeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::leaftest::TimeResponse*
Arena::CreateMaybeMessage< ::leaftest::TimeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leaftest::TimeResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
